### ISSUE TITLE
Does tooltip can be customized

### ISSUE THREAD

**Issue by knm100** [LBCrion/sfwbar#178]
the tooltip  is too big for me, I tried padding and margin.  it didn't seem like taking effect.

**Comment by LBCrion** [comment]
You can add this to your css section:

tooltip * { font-size: 10px; }

**Comment by knm100** [comment]
I tried two ways in CSS section as following,  both of they didn't take effect .  even the size of the font in tooltip had no any change.
1.
tooltip {
  background-color: @theme_bg_color;   /*the   content of offical T2 config */
  font-size: 10px;  /* add this line to change tooltip dimension,but nothing happened.*/
}

2.
/*tooltip {
  background-color: @theme_bg_color;
  font-size: 10px; 
} */
tooltip * { font-size: 10px; }

it seems to me that the reason probably is not the font size ,instead, the distance between the text and the border.

**Comment by knm100** [comment]
I found this problem with tooltips for almost every GTK program except chromium.

**Comment by LBCrion** [comment]
Try:

tooltip * {
  padding: 0px;
}

**Comment by knm100** [comment]
Thank your very much!   Only 0px can appear the effect, and more than 0px will not  appear the obvious effect or have no effect in the first place.

**Comment by knm100** [comment]
when i changed the tooltip backgroud-color,  The tooltip  looks like the one shown below
![6](https://github.com/LBCrion/sfwbar/assets/166389780/9d54ce15-9a78-47e4-b0e7-2c96e87d40d1)
The  section of tooltip is set up as follows:
tooltip * {
  background-color: #e1dedb;
  margin: 0px;
  border: none;
  padding: 0px;
}
I can chang the color of border frome black to #e1dedb?

**Comment by LBCrion** [comment]
try:

```
tooltip {
  border: none;
}
```

**Comment by knm100** [comment]
it  did not take effect.    Here's my context about tooltip.
tooltip * {
  background-color: @theme_bg_color;  
  margin: 0px;
  border: none;
  border-color: red;
  padding: 0px;
}
tooltip {
  border: none;
}

**Comment by LBCrion** [comment]
try setting tooltip background-color to `#e1dedb`? Essentially you have a `tooltip {}` section to control visualization of the tooltip itself and `tooltip * {}` for all widgets within the tooltip. If both are set to not have borders and to the same background color, there shouldn't be anything around the tooltip.

**Comment by knm100** [comment]
it worked. thank you!
by the way,   Is the range of effects of the "tooltip" and "tooltip *" different ？

**Comment by knm100** [comment]
it worked, thank your very much!

**Comment by knm100** [comment]
Does the above CSS code for tooptip  not work any more?

**Comment by knm100** [comment]
Does the above CSS code for tooptip  not work any more?

**Comment by LBCrion** [comment]
Tooltip css should work s usual.  Any particular tooltip you're trying to
style? The only change I've made is to tray item tooltips which should now
respect pango markup.

**Comment by knm100** [comment]
the below css code didn't work,  It worked before.
```
tooltip *  {
background-color: @theme_bg_color;
margin: 0px;
border: none;
border-color: red;
padding: 0px;
}
tooltip  {
border: none;
}

```

**Comment by knm100** [comment]
My main goal is to reduce the padding, but setting padding=0 doesn't change anything.

**Comment by LBCrion** [comment]
Is this for all widget tooltips or any particular one?

**Comment by knm100** [comment]
I have added the code to the end of the css section of sfwbar.config
But it still didn't work.
[sfwbar.config.txt](https://github.com/user-attachments/files/17567342/sfwbar.config.txt)
![swappy-20241030-145208](https://github.com/user-attachments/assets/69467cd8-c9de-477c-a43c-7644c1574514)

**Comment by LBCrion** [comment]
Do you have any other occurrences of the word  'tooltip' in your css style
sheet?

**Comment by knm100** [comment]
there is no more tooltip in all css style sheet( include main cofing file and widget)

**Comment by 01micko** [comment]
if `style = "launcher"` (as it is in most widgets in your config @knm100 ) does `tooltip#launcher { ... }` work?

**Comment by knm100** [comment]
@01micko  It don't work.

**Comment by knm100** [comment]
Does   `$HOME/.config/gtk-3.0/setting.ini`  affect tooltips? 
[settings.ini.txt](https://github.com/user-attachments/files/17569026/settings.ini.txt)

**Comment by 01micko** [comment]
> Does `$HOME/.config/gtk-3.0/setting.ini` affect tooltips? [settings.ini.txt](https://github.com/user-attachments/files/17569026/settings.ini.txt)

No. `gtk` themes themselves usually have something defined for `tooltip` Anything for tooltip defined in sfwbar should override that.

**Comment by 01micko** [comment]
Try this:

```css
tooltip *  {
  background-color: @theme_bg_color; 
  margin: 0px;
  border: none;
  padding: 0px;
}

tooltip  {
  border: none;
  background-color: rgba(0,0,0,0); /* transparent ? */
  padding: 0px;
  margin: 0px;
}
```

**Comment by knm100** [comment]
In order to see more clearly whether it works or not, I chose to change ` background-color: @theme_bg_color` to` background: green; `the following picture shows the actual effect
![swappy-20241030-182346](https://github.com/user-attachments/assets/2061f68f-1b88-4a0f-9457-6b991b685a15)

**Comment by LBCrion** [comment]
So it looks like the tooltip styling is working. You're just looking to
remove the margin around the contents of your tooltip. This is more of a
gtk question than sfwbar question. My simplistic suggestion would be to set
tooltip { background: rgba(0,0,0,0); } to make the margins transparent.

**Comment by knm100** [comment]
My feeling is that after setting  `tooltip  { background-color: red;}` color to`tooltip  { background-color: rgba(0,0,0,0);},` it just shows the green area that was originally covered by the red color, and doesn't change the size of the tooltips.
anyway, CSS CODE is in effect, it's just that by default it's the smallest size possible

**Comment by 01micko** [comment]
This is working for me

```css
tooltip {
  background-color: alpha(@theme_bg_color,0.0);
  font-size: 10px;
  border: none;
  color: @theme_fg_color;
}
tooltip label {
  background-color: @theme_bg_color;
  font-size: 10px;
  color: @theme_fg_color;
}
```
![tip](https://github.com/user-attachments/assets/80995c68-07d3-46c9-809c-13a5351e7f05)

You can give it radius too

```css
tooltip {
  background-color: alpha(@theme_bg_color,0.0);
  font-size: 10px;
  border: none;
  color: @theme_fg_color;
}
tooltip label {
  background-color: @theme_bg_color;
  font-size: 10px;
  border-radius: 5px;
  color: @theme_fg_color;
}
```
![tip2](https://github.com/user-attachments/assets/696b85aa-70e5-4950-a8e8-e2585dd5d769)
