### ISSUE TITLE
Help needed with styling tray icons

### ISSUE THREAD

**Issue by milochadam** [LBCrion/sfwbar#20]
Right now icons take all available height.
![image](https://user-images.githubusercontent.com/27895477/150659065-ec2770c5-a587-454f-a0d8-a49d2e91d26a.png)
I have a snippet like this but honestly I don't know what affects icon's size.
```css
image#tray_active, image#tray_passive, image#tray_attention {
    min-width: 0.40cm;
    min-height: 0.40cm;
    margin-left: 1mm;
    margin-right: 1mm;
}
```
I want to have some top and bottom margin, like the speaker icon in the sound widget:
![image](https://user-images.githubusercontent.com/27895477/150659110-2d0f821b-9b0b-48a1-8324-f9f02d28df55.png)
