### ISSUE TITLE
Please tell me how to reduce the height of the panel?

### ISSUE THREAD

**Issue by rediskap** [LBCrion/sfwbar#335]
Please tell me how to reduce the height of the panel?

**Comment by LBCrion** [comment]
There is no explicit setting for height, instead, you can specify height
for individual items and the height of the bar will adjust accordingly. For
a default config, you'll need to adjust min-height for:
1) button#startmenu image, button#module image
2) button#taskbar_item image
3) button#tray_image image

and if you want to make the bar thinner, you'll probably need to change the
clock widget from using 2 lines to using 1.

**Comment by AClon314** [comment]
> There is no explicit setting for height, instead, you can specify height
> for individual items and the height of the bar will adjust accordingly. For
> a default config, you'll need to adjust min-height for:
> 1) button#startmenu image, button#module image
> 2) button#taskbar_item image
> 3) button#tray_image image
> 
> and if you want to make the bar thinner, you'll probably need to change the
> clock widget from using 2 lines to using 1.
> […](#)

Hi @LBCrion , how can I set a global variable to set these 3 parts for convenience? I've tried these but failed:
```scss
Set BarHeight = "40px"
button#startmenu image,
button#module image {
  min-height: Str(BarHeight);
  min-width: Str(BarHeight);
  padding: 0px;
  margin: 0px;
  -GtkWidget-valign: center;
  -GtkWidget-vexpand: true;
}
button#taskbar_item image {
  min-width: Str(BarHeight);
  min-height: Str(BarHeight);
  padding-right: 6px;
  -ScaleImage-symbolic: false;
}
```
